main: org.polymart.mcplugin.Main
name: Polymart
version: "1.2.9"
api-version: "1.13"
author: Polymart
website: https://polymart.org
load: STARTUP
softdepend:
  - PlaceholderAPI
commands:
  polymart:
    description: Polymart commands
    usage: /polymart <update/search/login/logout/account/version/help>
    aliases: [pmt, pmrt]
  update:
    description: Update your plugins with Polymart
    usage: /update [plugin 1] [plugin 2] [plugin 3] [...]